version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: klaude
    main: ./cmd/klaude
    binary: klaude
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/kubestellar/klaude/internal/version.Version={{.Version}}
      - -X github.com/kubestellar/klaude/internal/version.BuildDate={{.Date}}
      - -X github.com/kubestellar/klaude/internal/version.GitCommit={{.Commit}}

archives:
  - id: klaude
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kubestellar
    name: klaude
  draft: false
  prerelease: auto

brews:
  - name: klaude
    repository:
      owner: kubestellar
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/kubestellar/klaude"
    description: "AI-powered multi-cluster Kubernetes management for Claude Code"
    license: "Apache-2.0"
    install: |
      bin.install "klaude"
    test: |
      system "#{bin}/klaude", "version"
