name: Assignment Helper

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assignment-helper:
    uses: kubestellar/infra/.github/workflows/reusable-assignment-helper.yml@220beeeb8dae67e2fd8e89338ada8144609fc6ef  # main
