name: Greetings

on:
  pull_request_target:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

permissions: read-all  # top-level default (least-privilege)

jobs:
  greet:
    if: >-
      github.event_name != 'pull_request_target' ||
      github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: kubestellar/infra/.github/workflows/reusable-greetings.yml@af322d48cc67ade7345cabc6a0ed55c6c7040ee4
