name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all  # default read; writes scoped to job below

jobs:
  analysis:
    permissions:
      security-events: write
      id-token: write
    uses: kubestellar/infra/.github/workflows/reusable-scorecard.yml@af322d48cc67ade7345cabc6a0ed55c6c7040ee4
