name: Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    uses: kubestellar/infra/.github/workflows/reusable-stale.yml@220beeeb8dae67e2fd8e89338ada8144609fc6ef  # main
    secrets: inherit
